# 项目：评估和清理英国电商公司销售数据

## 分析目标

此数据分析的目的是，根据市场销售数据，挖掘畅销产品，以便制定更有效的市场策略来提升营收。

本实战项目的目的在于练习评估数据干净和整洁度，并且基于评估结果，对数据进行清洗，从而得到可供下一步分析的数据。

## 简介

原始数据集记录了一家英国在线零售公司在2010年12月1日至2011年12月9日期间的所有交易情况，涵盖了该公司在全球不同国家和地区的业务数据。该公司主要销售覆盖各个场景的礼品，包括但不限于生日礼品、结婚纪念品、圣诞礼品等等。该公司的客户群体主要包括批发商和个人消费者，其中批发商占据了相当大的比例。

数据每列的含义如下：
- `InvoiceNo`: 发票号码。6位数，作为交易的唯一标识符。如果这个代码以字母“c”开头，表示这笔交易被取消。
- `StockCode`: 产品代码。5位数，作为产品的唯一标识符。
- `Description`: 产品名称。
- `Quantity`: 产品在交易中的数量。
- `InvoiceDate`: 发票日期和时间。交易发生的日期和时间。
- `UnitPrice`: 单价。价格单位为英镑（£）。
- `CustomerID`: 客户编号。5位数，作为客户的唯一标识符。
- `Country`: 国家名称。客户所居住的国家的名称。

## 读取数据

导入数据分析所需要的库，并通过Pandas的`read_csv`函数，将原始数据文件"e_commerce.csv"里的数据内容，解析为DataFrame，并赋值给变量`original_data`。

In [1]:
import pandas as pd

In [2]:
original_data=pd.read_csv('e_commerce.csv')

/var/folders/98/n7x2vqz573s7nwn4x0frgk5r0000gn/T/ipykernel_67067/1266749360.py:1: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  original_data=pd.read_csv('e_commerce.csv')

In [3]:
original_data.head()

,Unnamed: 0,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

## 评估数据

在这一部分，我将对在上一部分建立的`original_data`这个DataFrame所包含的数据进行评估。

评估主要从两个方面进行：结构和内容，即整齐度和干净度。数据的结构性问题指不符合“每列是一个变量，每行是一个观察值，每个单元格是一个值”这三个标准，数据的内容性问题包括存在丢失数据、重复数据、无效数据等。

### 评估数据整齐度

In [4]:
original_data.sample(10)

,Unnamed: 0,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
115079,117625,546394,22961,JAM MAKING SET PRINTED,12,2011-03-11 14:26:00,1.45,17164.0,United Kingdom
478079,488545,577834,22294,HEART FILIGREE DOVE SMALL,24,2011-11-22 10:21:00,1.25,17528.0,United Kingdom
164092,167907,551007,22507,MEMO BOARD RETROSPOT DESIGN,1,2011-04-26 09:49:00,10.79,NaN,United Kingdom
309958,317004,564757,23240,SET OF 4 KNICK KNACK TINS DOILY,2,2011-08-30 10:36:00,8.29,NaN,United Kingdom
273146,279461,561324,37327,ASSTD MULTICOLOUR CIRCLES MUG,48,2011-07-26 13:45:00,0.39,14414.0,United Kingdom
329131,336565,566393,23189,SET OF 12 FORK CANDLES,6,2011-09-12 12:45:00,2.89,13269.0,United Kingdom
317258,324517,565407,22566,FELTCRAFT HAIRBAND PINK AND PURPLE,1,2011-09-04 11:00:00,0.85,16983.0,United Kingdom
311607,318664,564837,35637A,IVORY STRING CURTAIN WITH POLE,1,2011-08-30 12:40:00,19.13,NaN,United Kingdom
26860,27395,538537,21754,HOME BUILDING BLOCK WORD,3,2010-12-13 10:41:00,5.95,12747.0,United Kingdom
67007,68340,541862,22646,CERAMIC STRAWBERRY CAKE MONEY BANK,4,2011-01-23 16:02:00,1.45,14068.0,United Kingdom

从抽样的10行数据数据来看，数据符合“每列是一个变量，每行是一个观察值，每个单元格是一个值”，具体来看每行是关于某商品的一次交易，每列是交易相关的各个变量，因此不存在结构性问题。

### 评估数据干净度

In [5]:
original_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 530691 entries, 0 to 530690
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Unnamed: 0   530691 non-null  int64
 1   InvoiceNo    530691 non-null  object
 2   StockCode    530691 non-null  object
 3   Description  530691 non-null  object
 4   Quantity     530691 non-null  int64
 5   InvoiceDate  530691 non-null  object
 6   UnitPrice    530691 non-null  float64
 7   CustomerID   397924 non-null  float64
 8   Country      530691 non-null  object
dtypes: float64(2), int64(2), object(5)
memory usage: 36.4+ MB

从输出结果来看，数据共有541909条观察值，而`Description`、`CustomerID`变量存在缺失值。

此外，`InvoiceDate`的数据类型应为日期，`CustomerID`的数据类型应为字符串，应当进行数据格式转换。

### 评估缺失数据

在了解`Description`存在缺失值后，根据条件提取出缺失观察值。

In [6]:
original_data[original_data['Description'].isnull()]

Empty DataFrame
Columns: [Unnamed: 0, InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

有1454条交易数据缺失`Description`变量值。

从输出结果来看，这些缺失`Description`的交易数据，`UnitPrice`都为0。为了验证猜想，我们增加筛选条件，看是否存在`Description`变量缺失且`UnitPrice`不为0的数据。

In [7]:
original_data[original_data['Description'].isnull()&(original_data['UnitPrice']!=0)]

Empty DataFrame
Columns: [Unnamed: 0, InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

筛选出来结果数量为0条，说明缺失`Description`值的数据，同时也不具备有效的`UnitPrice`值。
z
`Description`表示产品名称，`UnitPrice`表示产品单价，都是进行后续商品交易分析的重要变量。如果它们同时缺失/无效，我们认为数据无法提供有效含义，因此这些后续可以被删除。

`CustomerID`变量同样存在缺失值，因此也根据条件提取出缺失观察值。

In [8]:
original_data[original_data['CustomerID'].isnull()]

,Unnamed: 0,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1430,1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1431,1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,2010-12-01 14:32:00,2.51,NaN,United Kingdom
1432,1445,536544,21786,POLKADOT RAIN HAT,4,2010-12-01 14:32:00,0.85,NaN,United Kingdom
1433,1446,536544,21787,RAIN PONCHO RETROSPOT,2,2010-12-01 14:32:00,1.66,NaN,United Kingdom
1434,1447,536544,21790,VINTAGE SNAP CARDS,9,2010-12-01 14:32:00,1.66,NaN,United Kingdom
...,...,...,...,...,...,...,...,...,...
530322,541536,581498,85099B,JUMBO BAG RED RETROSPOT,5,2011-12-09 10:26:00,4.13,NaN,United Kingdom
530323,541537,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,2011-12-09 10:26:00,4.13,NaN,United Kingdom
530324,541538,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,2011-12-09 10:26:00,4.96,NaN,United Kingdom
530325,541539,581498,85174,S/4 CACTI CANDLES,1,2011-12-09 10:26:00,10.79,NaN,United Kingdom
530326,541540,581498,DOT,DOTCOM POSTAGE,1,2011-12-09 10:26:00,1714.17,NaN,United Kingdom

`CustomerID`表示客户编号，不是分析畅销商品的必要变量。并且从输出结果来看，有些`CustomerID`缺失的交易数据仍然有效，因此保留此变量为空的观察值。

### 评估重复数据

根据数据变量的含义来看，虽然InvoiceNo、StockCode和CustomerID都是唯一标识符，但一次交易可能包含多件商品，因此InvoiceNo可以存在重复，不同交易可以包含同件商品，因此StockCode可以存在重复，顾客可以进行多次交易或下单多个商品，因此CustomerID也可以存在重复。

那么针对此数据集，我们无需评估重复数据。

### 评估不一致数据

不一致数据可能存在于`Country`变量中，我们要查看是否存在多个不同值指代同一国家的情况。

In [9]:
original_data['Country'].value_counts()

Country
United Kingdom          485692
Germany                   9042
France                    8408
EIRE                      7894
Spain                     2485
Netherlands               2363
Belgium                   2031
Switzerland               1967
Portugal                  1501
Australia                 1185
Norway                    1072
Italy                      758
Channel Islands            748
Finland                    685
Cyprus                     614
Sweden                     451
Unspecified                446
Austria                    398
Denmark                    380
Poland                     330
Japan                      321
Israel                     295
China                      284
Singapore                  222
Iceland                    182
United States              179
Canada                     151
Greece                     145
Malta                      112
United Arab Emirates        68
European Community          60
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              25
Bahrain                     18
Saudi Arabia                 9
Name: count, dtype: int64

从`Country`变量值来看，`"USA"`、`"United States"`均在表示美国，`"United Kingdom"`、`"UK"`、`"U.K."`均在表示英国，因此应该在清洗步骤对这些值进行统一，只保留一个指代值。

### 评估无效或错误数据

可以通过DataFrame的`describe`方法，对数值统计信息进行快速了解。

In [10]:
original_data.describe()

          Unnamed: 0       Quantity      UnitPrice     CustomerID
count  530691.000000  530691.000000  530691.000000  397924.000000
mean   271299.338112      10.605855       3.903303   15294.315171
std    156572.469791     156.638147      35.896047    1713.169877
min         0.000000       1.000000       0.000000   12346.000000
25%    135584.500000       1.000000       1.250000   13969.000000
50%    271494.000000       3.000000       2.080000   15159.000000
75%    407147.500000      10.000000       4.130000   16795.000000
max    541908.000000   80995.000000   13541.330000   18287.000000

从输出结果来看，`Quantity`和`UnitPrice`存在负数，会对后续数值分析产生影响。

因此，我们先筛选出`Quantity`数值为负数的观察值，进一步评估其含义。

In [11]:
original_data[original_data['Quantity']<0]

Empty DataFrame
Columns: [Unnamed: 0, InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

从筛选结果来看，`Quantity`变量为负数的观察值，`InvoiceNo`似乎均以C开头，表示订单被取消。

但此猜测不一定准确，为了验证猜想，我们增加筛选条件，看是否存在`Quantity`变量为负数且`InvoiceNo`不以C开头的观察值。

In [12]:
original_data[(original_data['Quantity']<0)&(original_data['InvoiceNo'].str[0]!='C')]

Empty DataFrame
Columns: [Unnamed: 0, InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

以上猜想被证实错误，因为还存在`Quantity`变量为负数且`InvoiceNo`不以C开头的观察值。

但根据以上输出结果，这些筛选出的观察值的`UnitPrice`观察值均为0，因此增加`UnitPrice`的条件进行验证。

In [13]:
original_data[(original_data['Quantity']<0)&(original_data['InvoiceNo'].str[0]!='C')&(original_data['UnitPrice']!=0)]

Empty DataFrame
Columns: [Unnamed: 0, InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

根据输出结果，猜想得到验证，当`Quantity`变量为负数的时候，观察值满足以下条件之一：
- `InvoiceNo`以C开头，表示订单被取消
- `UnitPrice`为0，说明单价为0英镑

这些交易数据均不是有效成交数据，不贡献销售，不在后续分析范围内，因此我们将在数据清理步骤，将`Quantity`为负数的观察值删除。

接下来筛选出`UnitPrice`为负数的观察值。

In [14]:
original_data[original_data['UnitPrice']<0]

Empty DataFrame
Columns: [Unnamed: 0, InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

## 清理数据

根据前面评估部分得到的结论，我们需要进行的数据清理包括：
- 把`Description`变量缺失的观察值删除
- 把`Quantity`变量值为负数的观察值删除
- 把`UnitPrice`变量值为负数的观察值删除
- 把`InvoiceDate`变量的数据类型转换为为日期时间
- 把`CustomerID`变量的数据类型转换为字符串
- 把`Country`变量值`"USA"`替换为`"United States"`
- 把`Country`变量值`"UK"`、`"U.K."`替换为`"United Kingdom"`

 为了区分开经过清理的数据和原始的数据，我们创建新的变量`cleaned_data`，让它为`original_data`复制出的副本。我们之后的清理步骤都将被运用在`cleaned_data`上。

In [15]:
cleaned_data= original_data.copy()
cleaned_data.head()

,Unnamed: 0,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

把`Description`变量缺失的观察值删除，并查看删除后该列空缺值个数和：

In [16]:
cleaned_data.dropna(subset=['Description'],inplace=True)
cleaned_data['Description'].isnull().sum()

np.int64(0)

把`Quantity`变量值为负数的观察值删除，并检查替换后`Quantity`变量值不为正数的个数：

In [17]:
cleaned_data=cleaned_data[cleaned_data['Quantity']>0]
cleaned_data[cleaned_data['Quantity']<=0]

Empty DataFrame
Columns: [Unnamed: 0, InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

把`UnitPrice`变量值为负数的观察值删除，并检查替换后`UnitPrice`变量值为负数的个数：

In [18]:
cleaned_data=cleaned_data[cleaned_data['UnitPrice']>=0]
cleaned_data[cleaned_data['UnitPrice']<0]

Empty DataFrame
Columns: [Unnamed: 0, InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

把InvoiceDate变量的数据类型转换为为日期时间类型：

In [19]:
cleaned_data['InvoiceDate']=pd.to_datetime(cleaned_data['InvoiceDate'])
cleaned_data['InvoiceDate']

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
530686   2011-12-09 12:50:00
530687   2011-12-09 12:50:00
530688   2011-12-09 12:50:00
530689   2011-12-09 12:50:00
530690   2011-12-09 12:50:00
Name: InvoiceDate, Length: 530691, dtype: datetime64[ns]

把CustomerID变量的数据类型转换为字符串

In [20]:
cleaned_data['CustomerID']=cleaned_data['CustomerID'].astype(str)
cleaned_data['CustomerID']

0         17850.0
1         17850.0
2         17850.0
3         17850.0
4         17850.0
           ...
530686    12680.0
530687    12680.0
530688    12680.0
530689    12680.0
530690    12680.0
Name: CustomerID, Length: 530691, dtype: object

把`Country`变量值`"USA"`替换为`"United States"`

并检查替换后"USA"变量值个数：

In [21]:
cleaned_data['Country']=cleaned_data['Country'].replace({'USA':'United States'})
cleaned_data['Country']
print(len(cleaned_data[cleaned_data['Country']=='USA']))

0

把`Country`变量值`"UK"`、`"U.K."`替换为`"United Kingdom"`

并检查替换后"USA"变量值个数：

In [22]:
cleaned_data['Country']=cleaned_data['Country'].replace({'UK':'United Kingdom','U.K.':'United Kingdom'})
print(len(cleaned_data[cleaned_data['Country']=='UK']))
print(len(cleaned_data[cleaned_data['Country']=='U.K.']))

0
0

## 保存清理后的数据

完成数据清理后，把干净整齐的数据保存到新的文件里，文件名为e_commerce_cleaned.csv。

完成数据清理后，把干净整齐的数据保存到新的文件里，文件名为`e_commerce_cleaned.csv`。

In [23]:
cleaned_data.sample(5)

,Unnamed: 0,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
454926,465010,576200,23215,JINGLE BELL HEART ANTIQUE SILVER,6,2011-11-14 12:14:00,2.08,15572.0,United Kingdom
257685,263616,560024,47566,PARTY BUNTING,3,2011-07-14 13:00:00,4.95,15005.0,United Kingdom
344255,351986,567670,22572,ROCKING HORSE GREEN CHRISTMAS,1,2011-09-21 15:32:00,1.63,nan,United Kingdom
195722,200209,554117,22505,MEMO BOARD COTTAGE DESIGN,2,2011-05-22 15:12:00,4.95,13758.0,United Kingdom
388414,397406,571183,21070,VINTAGE BILLBOARD MUG,3,2011-10-14 11:08:00,1.25,14796.0,United Kingdom

In [29]:
cleaned_data.to_csv('e_commerce_cleaned.csv',index=False)
pd.read_csv('e_commerce_cleaned.csv').sample(5)

/var/folders/98/n7x2vqz573s7nwn4x0frgk5r0000gn/T/ipykernel_67067/2722328789.py:2: DtypeWarning: Columns (1) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv('e_commerce_cleaned.csv').sample(5)

,Unnamed: 0,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
427471,437135,574269,82483,WOOD 2 DRAWER CABINET WHITE FINISH,2,2011-11-03 14:27:00,6.95,15570.0,United Kingdom
10627,10772,537237,85132A,CHARLIE + LOLA BISCUITS TINS,2,2010-12-06 09:58:00,8.47,NaN,United Kingdom
304444,311413,564300,22030,SWALLOWS GREETING CARD,12,2011-08-24 11:31:00,0.42,16723.0,United Kingdom
196722,201235,554275,21381,MINI WOODEN HAPPY BIRTHDAY GARLAND,5,2011-05-23 13:17:00,1.69,14903.0,United Kingdom
45223,46215,540352,22317,FIVE CATS HANGING DECORATION,4,2011-01-06 14:27:00,2.51,NaN,United Kingdom